######### bindings
spring.cloud.stream.bindings.processCustomerTransactions-in-0:
  destination: Transaction
spring.cloud.stream.bindings.processCustomerTransactions-in-1:
  destination: Customer
spring.cloud.stream.bindings.processCustomerTransactions-out:
  destination: CustomerBalance
  producer:
    nativeEncoding: true
spring.cloud.stream.kafka.streams.bindings.processCustomerTransactions-out:
  producer:
    nativeEncoding: true
    content-type: application/*+avro



######### ######### ######### #########
spring.cloud.stream.function.definition: processCustomerTransactions
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

server:
  port: 9080
spring:
  kafka:
    streams:
      binder:
        applicationId: kafka-streams-test-id

      properties:
        bootstrap.servers: localhost:9092
        schema.registry.url: http://localhost:8081
        auto.commit.interval.ms: 100
    consumer:
      group-id: my-microservice
      auto-offset-reset: latest
      properties:
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
logging:
  level:
    root: info
spring.application.name: kafka-streams-test